expname: ${model.name}_${postfix}
postfix: ""
project: GPWNO

pdir: /home/holywater2/crystal

# metadata specialised for each experiment
core:
  version: 1.0.0
  tags:
    - ${now:%Y-%m-%d}

hydra:
  run:
    dir: ${oc.env:HYDRA_JOBS}/singlerun/${now:%Y-%m-%d-%H-%M-%S}/${expname}/

  sweep:
    dir: ${oc.env:HYDRA_JOBS}/multirun/${now:%Y-%m-%d}/${expname}/
    subdir: ${hydra.job.num}_${hydra.job.id}

  job:
    env_set:
      WANDB_START_METHOD: thread
      WANDB_DIR: ${oc.env:WANDB_DIR}

defaults:
  - data: default
  - logging: default
  - model: infgcn
  - optim: default
  - train: default
#    Decomment this parameter to get parallel job running
  # - override hydra/launcher: joblib