name: GPWNO_mk-${model.scalar_mask}_co${model.cutoff}_pc${model.probe_cutoff}_gc${model.grid_cutoff}_f${model.num_fourier}_fm${model.fourier_mode}_t${model.num_fourier_time}_w${model.width}_sp${model.num_spherical}_spf${model.num_spherical_RNO}_inp-${model.input_infgcn}_sha-${model.model_sharing}_max-${model.use_max_cell}_res-${model.residual}_mc${model.mask_cutoff}_ff-${model.using_ff}
_target_: source.models.GPWNO_test.GPWNO

n_atom_type: ${data.n_atom_type}
num_radial: 16
num_spherical: 3
radial_embed_size: 64
radial_hidden_size: 128
num_radial_layer: 2
num_gcn_layer: 2
cutoff: 3.0
is_fc: False
gauss_start: 0.5
gauss_end: 5.
residual: True
pbc: true
activation: "norm"

num_fourier: 20
num_fourier_time: 12
width: 16
fourier_mode: 0 # 0 -> (num_fourier // 2) else fourier_mode 

padding: 0
use_max_cell: False
max_cell_size: 324
equivariant_frame: false

probe_cutoff: 1.5
grid_cutoff: 0.75

# probe_and_node: False
# product: False

normalize: True

using_ff: True # Factorized Fourier
model_sharing: False
num_infgcn_layer: 3
use_detach: False

num_spherical_RNO: 3
scalar_mask: True
mask_cutoff: 1.0

input_infgcn: False

output_positive: False

atom_info : ${data.atom_file}

input_dist: False
atomic_gauss_dist: False