optimizer:
  #  Adam-oriented deep learning
  _target_: torch.optim.Adam
  #  These are all default parameters for the Adam optimizer
  lr: 5e-3
  betas: [ 0.9, 0.999 ]
  eps: 1e-08
  weight_decay: 1e-12

use_lr_scheduler: True

lr_scheduler_freq: ${logging.val_check_interval}

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  factor: 0.5
  patience: 5
  min_lr: 1e-5
  mode: "max" #should be min